name: Scheduled-Build
on:
  schedule:
    - cron: '* 25 * * *'

jobs:
  jekyll:
    runs-on: ubuntu-18.04
    steps:
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
