name: Scheduled-Build
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  jekyll:
    runs-on: ubuntu-18.04
    steps:
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: true
